### ISSUE TITLE
Using RJSON instead of JSON for default configuration

### ISSUE THREAD

**Issue by Himujjal** [abenz1267/neoconf#1]
I would like to suggest using [RJSON](https://rome.tools/#rome-json) over JSON for users to configure writing neoconf configs.

I know JSON is universal and all. RJSON takes 1 minute to learn anyways. I have already written a serializer/deserializer for it in C, [ekon](https://github.com/ekon-org/ekon) I will port it to Go within this week if you agree to go forward with it. API will be the same as JSON.

BTW. I would like to get involved more on this project.

**Comment by abenz1267** [comment]
Hello,

Thanks for your suggestion. I don't think there'd be any benefit introducing this dependency. Ideally users wouldn't touch a neoconf json anyways. The goal is to move away from manually editing files.

There's a lot to be done, so contribution in any form are welcomed. Ideas like this, PRs, discussions... Anything.

Regards

**Comment by Himujjal** [comment]
One RJSON file for project management would be great. Don't you think. Sort of like `coc-settings.json`. Simply run `neoconf -f config.rjson` and you have a neovim setup ready. Of course this config file will be highly abstracted.

One more use case is VS Code like snippets. RJSON supports multiline strings which could be a bane for snippets in general. Something like https://github.com/norcalli/snippets.nvim can be used for the same.

I assume this config focuses highly on the IDE aspect of Neovim that is so hard to configure.

**Comment by Himujjal** [comment]
Can you open github discussions for the repo?

**Comment by abenz1267** [comment]
> Can you open github discussions for the repo?

Should be available already. 



> One RJSON file for project management would be great. Don't you think. Sort of like `coc-settings.json`. Simply run `neoconf -f config.rjson` and you have a neovim setup ready. Of course this config file will be highly abstracted.
> 
> One more use case is VS Code like snippets. RJSON supports multiline strings which could be a bane for snippets in general. Something like https://github.com/norcalli/snippets.nvim can be used for the same.
> 
> I assume this config focuses highly on the IDE aspect of Neovim that is so hard to configure.

Yes, the focus is editor setup and I don’t intend to expand that scope, as it should be big enough already.

You haven’t provided any information on how RJSON would be beneficial in context of neoconf. Feel free to continue discussing via discussions, so it doesn’t get lost. 

Closing this issue for now.
